requires 'Mojolicious';
requires 'DBD::mysql';
requires 'DBIx::Encoding';
requires 'DBIx::Class';
requires 'DBIx::Class::Validation';
requires 'DateTime';
requires 'DateTime::Format::Strptime';
requires 'DateTime::Format::MySQL';
requires 'FormValidator::Simple::Plugin::DBIC::Unique';
requires 'DateTime::Set'
